"""Add Lesson model and update Section relationships

Revision ID: 6152ba9fa1f8
Revises: e9c0c2e251cb
Create Date: 2025-12-24 14:23:46.832230

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6152ba9fa1f8'
down_revision = 'e9c0c2e251cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('section_feedback')
    op.drop_table('section_progress')
    # 1. Add course_id as nullable and ensure id is primary key
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=True))  # Already exists
        batch_op.alter_column('id',
            existing_type=sa.INTEGER(),
            nullable=False,
            autoincrement=True,
            existing_primary_key=True)
        batch_op.alter_column('title',
            existing_type=sa.VARCHAR(length=200),
            nullable=False)
        batch_op.drop_column('is_active')
        batch_op.drop_column('teacher_id')
    # 1b. Add primary key constraint if not present (defensive)
    op.create_primary_key('pk_lessons', 'lessons', ['id'])
    # 1c. Add foreign key after PK
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'courses', ['course_id'], ['id'])

    # 2. Backfill all lessons with course_id=5 (Programming Documentation)
    op.execute('UPDATE lessons SET course_id=5 WHERE course_id IS NULL')

    # 3. Alter course_id to NOT NULL
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.alter_column('course_id', existing_type=sa.Integer(), nullable=False)

    # 4. Add lesson_id as nullable to sections
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lesson_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_sections_course'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'lessons', ['lesson_id'], ['id'])
        batch_op.drop_column('course_id')


    # 5. Backfill each section's lesson_id based on lesson and section titles
    # Module 1: Commenting
    op.execute("""
        UPDATE sections SET lesson_id = (SELECT id FROM lessons WHERE title = 'Module 1: Commenting' LIMIT 1)
        WHERE title IN (
            'Introduction to Code Comments',
            'Section 1: Python Comments - Best Practices',
            'Section 2: JavaScript Comments - Best Practices',
            'Section 3: HTML and CSS Comments - Best Practices'
        )
    """)
    # Module 2: Debugging
    op.execute("""
        UPDATE sections SET lesson_id = (SELECT id FROM lessons WHERE title = 'Module 2: Debugging' LIMIT 1)
        WHERE title IN (
            'Introduction to Code Debugging',
            'Section 1: Python Debugging - Best Practices',
            'Section 2: JavaScript Debugging - Best Practices',
            'Section 3: HTML and CSS Debugging - Best Practices'
        )
    """)
    # Module 3: Assessment Checking
    op.execute("""
        UPDATE sections SET lesson_id = (SELECT id FROM lessons WHERE title = 'Module 3: Assessment Checking' LIMIT 1)
        WHERE title IN (
            'Checking Overview',
            'Lesson 1: Comment Checker',
            'Lesson 2: Debug Checker'
        )
    """)
    # Module 4: Realtime Commenting and Debugging With AI
    op.execute("""
        UPDATE sections SET lesson_id = (SELECT id FROM lessons WHERE title = 'Module 4: Realtime Commenting and Debugging With AI' LIMIT 1)
        WHERE title IN (
            'Coding with AI',
            'Assessment Specific and AI'
        )
    """)

    # 6. Alter lesson_id to NOT NULL
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.alter_column('lesson_id', existing_type=sa.Integer(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_sections_course'), 'courses', ['course_id'], ['id'])
        batch_op.drop_column('lesson_id')

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('course_id')

    op.create_table('section_progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('section_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], name=op.f('section_progress_section_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('section_progress_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('section_progress_pkey'))
    )
    op.create_table('section_feedback',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('section_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('clarity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('difficulty', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('engagement', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], name=op.f('section_feedback_section_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('section_feedback_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('section_feedback_pkey'))
    )
    # ### end Alembic commands ###
