"""Initial migration after Alembic reset

Revision ID: e9c0c2e251cb
Revises: 
Create Date: 2025-12-24 13:07:16.458999

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e9c0c2e251cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('lessons')
    # op.drop_table('section_feedback')
    # op.drop_table('section_progress')
    with op.batch_alter_table('comment_feedback', schema=None) as batch_op:
        # 1. Add as nullable
        batch_op.add_column(sa.Column('section_id', sa.Integer(), nullable=True))
    # 2. Delete all old comment_feedback rows before enforcing NOT NULL and foreign key
    op.execute('DELETE FROM comment_feedback')
    with op.batch_alter_table('comment_feedback', schema=None) as batch_op:
        # 3. Set NOT NULL
        batch_op.alter_column('section_id', nullable=False)
        batch_op.alter_column('code_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_server_default=sa.text("'unknown'::character varying"))
        batch_op.create_foreign_key(None, 'sections', ['section_id'], ['id'])
        batch_op.drop_column('lesson_id')

    with op.batch_alter_table('lesson_feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section_id', sa.Integer(), nullable=False))
        # batch_op.drop_constraint(batch_op.f('lesson_feedback_lesson_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'sections', ['section_id'], ['id'])
        batch_op.drop_column('lesson_id')

    with op.batch_alter_table('lesson_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section_id', sa.Integer(), nullable=False))
        # batch_op.drop_constraint(batch_op.f('lesson_progress_lesson_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'sections', ['section_id'], ['id'])
        batch_op.drop_column('lesson_id')

    with op.batch_alter_table('sections', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=False))
        # batch_op.drop_constraint(batch_op.f('sections_lesson_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'courses', ['course_id'], ['id'])
        batch_op.drop_column('lesson_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=False))
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('sections_lesson_id_fkey'), 'lessons', ['lesson_id'], ['id'])
        batch_op.drop_column('course_id')

    with op.batch_alter_table('lesson_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=False))
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('lesson_progress_lesson_id_fkey'), 'lessons', ['lesson_id'], ['id'])
        batch_op.drop_column('section_id')

    with op.batch_alter_table('lesson_feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=False))
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('lesson_feedback_lesson_id_fkey'), 'lessons', ['lesson_id'], ['id'])
        batch_op.drop_column('section_id')

    with op.batch_alter_table('comment_feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=False))
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('comment_feedback_lesson_id_fkey'), 'lessons', ['lesson_id'], ['id'])
        batch_op.alter_column('code_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_server_default=sa.text("'unknown'::character varying"))
        batch_op.drop_column('section_id')

    op.create_table('section_progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('section_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], name=op.f('section_progress_section_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('section_progress_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('section_progress_pkey'))
    )
    op.create_table('section_feedback',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('section_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('clarity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('difficulty', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('engagement', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], name=op.f('section_feedback_section_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('section_feedback_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('section_feedback_pkey'))
    )
    op.create_table('lessons',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('template_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('video_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('lessons_course_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('lessons_pkey'))
    )
    # ### end Alembic commands ###
